### Crear un nuevo usuario
POST http://localhost:9785/api/create-user HTTP/1.1
content-type: application/json

{
    "username": "Karasowl",
    "email": "karasowl@email.com",
    "password": "@Karasowl0"
}
